
server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #payment_route      #路由的ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE       #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**              # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001         #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE      #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**              # 断言，路径相匹配的进行路由
            - After=2023-02-05T16:51:46.573650400+08:00[Asia/Shanghai]
#            - Cookie=username, zhangsan

eureka:
  instance:
    hostname: gateway9527
    prefer-ip-address: true
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka

